# Generated by Django 4.2.7 on 2026-04-20 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Скидка'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('discount_type', models.CharField(choices=[('percentage', 'Процент (%)'), ('fixed', 'Фиксированная сумма (₽)')], max_length=20, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Размер скидки')),
                ('min_cart_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Мин. сумма корзины (₽)')),
                ('first_order_only', models.BooleanField(default=False, verbose_name='Только первый заказ')),
                ('usage_limit', models.PositiveIntegerField(default=0, verbose_name='Лимит использований (0 = ∞)')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Использован раз')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Только для категории')),
                ('product_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='Только для товара')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promocode', verbose_name='Промокод'),
        ),
    ]
