# Generated by Django 4.2.7 on 2026-04-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount_amount_promocode_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addr_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='order',
            name='addr_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
