# Generated by Django 4.2.7 on 2026-04-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_encrypt_existing_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Хэш email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='Хэш телефона'),
        ),
    ]
