# Generated by Django 4.2.7 on 2026-04-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_email_hash_alter_user_phone_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.TextField(verbose_name='Номер телефона (зашифрован)'),
        ),
    ]
